# This is a basic workflow to help you get started with Actions

name: Sync Notion Star

# Controls when the workflow will run
on:
  #schedule:
  #  - cron:  '*/5 * * * *'
  
  workflow_dispatch:

jobs:
  full-sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/.cache
          key: ${{ hashFiles('**/.cache') }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          always-auth: false
          node-version: 16.x
          cache: yarn

      - name: Run Sync
        run: npm start
