# This is a basic workflow to help you get started with Actions
name: Sync Notion Star

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  full-sync:
    runs-on: ubuntu-latest
    environment: notion-sync
    steps:
      - name: Download artifact of last build
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          workflow: blank.yml
          workflow_conclusion: success
          name: notion-sync-storage
          path: .cache
          
      - run: ls -al && ls .cache && cat .cache/notion-page.json
         
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          always-auth: false
          node-version: 16.x
          cache: yarn

      - run: yarn

      - name: Run Sync
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          TOKEN_OF_GITHUB: ${{ secrets.TOKEN_OF_GITHUB }}
          FULLSYNC_LIMIT: 2000
          PARTIALSYNC_LIMIT: 10
          SYNC_NOTION_FIRST: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: npm start
        
      - uses: actions/upload-artifact@v2
        with:
          name: notion-sync-storage
          path: .cache
